### ISSUE TITLE
Minor Edits to Q1-2

### ISSUE THREAD

**Issue by esme-castro** [mandiward17/hw1#8]
Hi team! If anyone has the time to look at Q1-2, I need some help with adjusting the width (I think in the geom_errorbarh() and geom_linerange()) so that three countries' error lines do not disappear (look at France for example). I also left this same comment at the bottom of each code chunk. Thanks!

**Comment by ZF-MPH** [comment]
I will give it a shot :)

**Comment by esme-castro** [comment]
Thanks for looking at Q1. I fixed Q2 with the same function!
